# Generated by Django 6.0.5 on 2026-06-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('recruiter', 'Recruiter'), ('client', 'Client'), ('corporate_client', 'Corporate Client')], default='client', max_length=20),
        ),
    ]
