# Generated by Django 6.0.5 on 2026-06-18 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiters_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='recruiter_type',
            field=models.CharField(blank=True, choices=[('cwr', 'CWR'), ('fte', 'FTE')], help_text='Classification for recruiters (CWR or FTE)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('recruiter', 'Recruiter'), ('client', 'Client'), ('corporate_client', 'Corporate Client'), ('manager', 'Manager'), ('ceo', 'CEO')], default='client', max_length=20),
        ),
    ]
