# Generated by Django 6.0.5 on 2026-07-15 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_manager_user_recruiter_type_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='corporate_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='myspace.corporateclient'),
        ),
    ]
