# Generated by Django 6.0.5 on 2026-05-26 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('full_name', models.CharField(max_length=255)),
                ('years_of_experience', models.PositiveIntegerField(help_text='Years of professional experience')),
                ('rate_card', models.DecimalField(decimal_places=2, help_text='Rate card in USD (hourly/monthly)', max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('availability', models.CharField(help_text='e.g. Immediate, 2 Weeks Notice, 1 Month Notice', max_length=100)),
                ('summary', models.TextField(help_text='Summary or notes about the candidate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to=settings.AUTH_USER_MODEL)),
                ('technical_stack', models.ManyToManyField(related_name='candidates', to='teams.technologystack')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
