# Generated by Django 6.0.5 on 2026-05-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Summary or notes about the candidate'),
        ),
    ]
