# Generated by Django 6.0.5 on 2026-05-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.CharField(blank=True, default='', help_text='e.g. Python, React (comma-separated)', max_length=255),
        ),
    ]
