# Generated by Django 6.0.5 on 2026-05-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_job_title_candidate_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_on_hold',
            field=models.BooleanField(default=False, help_text='If checked, this candidate is on hold and invisible to clients.'),
        ),
    ]
