# Generated by Django 6.0.5 on 2026-06-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidate_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='employment_type',
            field=models.CharField(default='Full Time', help_text='Employment type: Full Time, Contract, Remote', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='salary_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salary in INR per annum', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='availability',
            field=models.CharField(default='Immediate', help_text='Notice period / availability', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='rate_card',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate card in USD per hour', max_digits=10, null=True),
        ),
    ]
