# Generated by Django 6.0.5 on 2026-06-10 11:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='corporate_candidates/photos/')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('total_experience', models.CharField(help_text='e.g. 5 Years, 8.5 Years', max_length=100)),
                ('current_location', models.CharField(max_length=255)),
                ('technology_stack', models.CharField(help_text='e.g. SAP, Python, React, DevOps – free-form text, no restrictions', max_length=255)),
                ('current_company', models.CharField(blank=True, default='', max_length=255)),
                ('rate_card', models.DecimalField(decimal_places=2, help_text='Rate card in USD', max_digits=10)),
                ('resume', models.FileField(blank=True, null=True, upload_to='corporate_candidates/resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('placed', 'Placed'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(limit_choices_to={'role': 'recruiter'}, on_delete=django.db.models.deletion.CASCADE, related_name='corporate_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corporate Candidate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorporateClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Company / Organisation Name', max_length=255)),
                ('company_website', models.URLField(blank=True, default='', max_length=300)),
                ('industry', models.CharField(blank=True, default='', max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'corporate_client'}, on_delete=django.db.models.deletion.CASCADE, related_name='corporate_client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corporate Client',
                'verbose_name_plural': 'Corporate Clients',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('required_skills', models.TextField()),
                ('experience', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('rate_card', models.CharField(help_text='e.g. $80/hr or $120k/yr', max_length=100)),
                ('employment_type', models.CharField(help_text='e.g. Contract, Full-Time, Part-Time', max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('on_hold', 'On Hold'), ('filled', 'Filled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requirements', to='myspace.corporateclient')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_job_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Requirement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('viewed', 'Viewed'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='submitted', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_submissions', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='myspace.corporatecandidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='myspace.jobrequirement')),
            ],
            options={
                'verbose_name': 'Candidate Submission',
                'ordering': ['-created_at'],
                'unique_together': {('job', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_status_changes', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='myspace.candidatesubmission')),
            ],
            options={
                'verbose_name': 'Submission Status History',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='myspace.corporatecandidate')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='myspace.corporateclient')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='myspace.jobrequirement')),
            ],
            options={
                'verbose_name': 'Candidate Cart Item',
                'ordering': ['-created_at'],
                'unique_together': {('client', 'job', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='RecruiterClientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_assignments', to='myspace.corporateclient')),
                ('recruiter', models.ForeignKey(limit_choices_to={'role': 'recruiter'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruiter–Client Assignment',
                'ordering': ['-assigned_at'],
                'unique_together': {('recruiter', 'client')},
            },
        ),
    ]
