# Generated by Django 6.0.5 on 2026-06-12 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateCredentialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_requests', to='myspace.corporatecandidate')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_requests', to='myspace.corporateclient')),
            ],
            options={
                'verbose_name': 'Corporate Credential Request',
                'verbose_name_plural': 'Corporate Credential Requests',
                'ordering': ['-created_at'],
                'unique_together': {('client', 'candidate')},
            },
        ),
    ]
