# Generated by Django 6.0.5 on 2026-06-15 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0002_corporatecredentialrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatecandidate',
            name='bgv_verification',
            field=models.FileField(blank=True, null=True, upload_to='corporate_candidates/bgv_verifications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='corporatecandidate',
            name='evaluation_certificate',
            field=models.FileField(blank=True, null=True, upload_to='corporate_candidates/evaluation_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
