# Generated by Django 6.0.5 on 2026-07-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0005_corporatecandidate_employment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequirement',
            name='num_positions',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of Positions'),
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='onboard_type',
            field=models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('In Office Everyday', 'In Office Everyday')], default='Remote', max_length=50, verbose_name='Onboard Type'),
        ),
        migrations.AlterField(
            model_name='candidatesubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('viewed', 'Viewed'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('selected_yet_to_offer', 'Select Yet to Offer'), ('offered_yet_to_join', 'Offered yet to Join'), ('joined', 'Joined'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='submitted', max_length=30),
        ),
    ]
