# Generated by Django 6.0.5 on 2026-07-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0006_jobrequirement_num_positions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequirement',
            name='notice_period',
            field=models.CharField(choices=[('Immediate', 'Immediate'), ('15 Days', '15 Days'), ('1 Month', '1 Month'), ('2 Months', '2 Months'), ('3 Months', '3 Months')], default='Immediate', max_length=100, verbose_name='Notice Period'),
        ),
    ]
