# Generated by Django 6.0.5 on 2026-07-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0007_jobrequirement_notice_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatecandidate',
            name='servicenow_module',
            field=models.CharField(blank=True, choices=[('ITSM', 'ITSM'), ('ITOM', 'ITOM'), ('HRSD', 'HRSD'), ('CSM', 'CSM'), ('SPM', 'SPM'), ('IRM_GRC', 'IRM/GRC'), ('SecOps', 'SecOps'), ('HAM', 'HAM'), ('SAM_Pro', 'SAM Pro'), ('FSM', 'FSM')], max_length=50, null=True, verbose_name='ServiceNow Module'),
        ),
        migrations.AddField(
            model_name='corporateclient',
            name='is_servicenow_client',
            field=models.BooleanField(default=False, verbose_name='Is ServiceNow Client'),
        ),
    ]
