# Generated by Django 6.0.5 on 2026-07-07 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0008_corporatecandidate_servicenow_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatecandidate',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Optional: Associate candidate with a corporate client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='myspace.corporateclient'),
        ),
        migrations.AddField(
            model_name='corporatecandidate',
            name='ltm_ripple_ats_check',
            field=models.CharField(blank=True, choices=[('duplicate', 'Duplicate'), ('not_duplicate', 'Not Duplicate')], max_length=20, null=True, verbose_name='LTM Ripple ATS Check'),
        ),
    ]
