# Generated by Django 6.0.5 on 2026-07-15 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def migrate_client_data(apps, schema_editor):
    CorporateClient = apps.get_model('myspace', 'CorporateClient')
    User = apps.get_model('accounts', 'User')
    CandidateCart = apps.get_model('myspace', 'CandidateCart')
    
    # 1. Migrate CorporateClient.user (OneToOneField) to User.corporate_client (ForeignKey)
    for client in CorporateClient.objects.all():
        if hasattr(client, 'user_id') and client.user_id:
            try:
                user = User.objects.get(pk=client.user_id)
                user.corporate_client = client
                user.save()
            except User.DoesNotExist:
                pass

    # 2. Migrate CandidateCart.client to CandidateCart.user
    for item in CandidateCart.objects.all():
        if item.client_id:
            try:
                client = CorporateClient.objects.get(pk=item.client_id)
                user = User.objects.filter(role='corporate_client', corporate_client=client).first()
                if user:
                    item.user = user
                    item.save()
            except Exception:
                pass

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('myspace', '0009_corporatecandidate_client_and_more'),
        ('accounts', '0004_user_corporate_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_cart_items', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.RunPython(migrate_client_data, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='candidatecart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_cart_items', to=settings.AUTH_USER_MODEL, null=False),
        ),
        migrations.AlterUniqueTogether(
            name='candidatecart',
            unique_together={('user', 'job', 'candidate')},
        ),
        migrations.RemoveField(
            model_name='corporateclient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='candidatecart',
            name='client',
        ),
    ]
