# Generated by Django 6.0.5 on 2026-05-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationLog',
        ),
    ]
